name: mineral
description: Mineral is a Discord framework for designing discord bots in Dart.
version: 4.0.0-dev.11

repository: https://github.com/mineral-dart/core
# homepage: https://www.example.com

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.3.1
  path: ^1.8.2
  http: ^1.1.0
  collection: ^1.16.0
  recase: ^4.1.0
  watcher: ^1.1.0
  logging: ^1.2.0
  rxdart: ^0.27.7
  win32: ^5.4.0
  intl: ^0.19.0
  yaml: ^3.1.2
  mansion: ^0.1.0
  uuid: ^4.4.2
  eterl: ^1.1.0
  env_guard: ^1.3.1
  hmr:
    path: ../../hmr/hmr
  glob: ^2.1.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
