name: mineral
description: Mineral is a Discord framework for designing discord bots in Dart.
version: 3.1.0

repository: https://github.com/mineral-dart/core
# homepage: https://www.example.com

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  args: ^2.3.1
  path: ^1.8.2
  http: ^1.1.0
  collection: ^1.16.0
  recase: ^4.1.0
  prompts: ^2.0.0
  tint: ^2.0.1
  watcher: ^1.1.0
  logging: ^1.2.0
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^2.1.1
  test: ^1.16.0
