name: mineral
description: Mineral is a Discord framework for designing discord bots in Dart.
version: 4.2.0

repository: https://github.com/mineral-dart/core
# homepage: https://www.example.com

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.7.0
  path: ^1.9.1
  http: ^1.6.0
  collection: ^1.19.1
  recase: ^4.1.0
  watcher: ^1.1.4
  logging: ^1.3.0
  win32: ^5.15.0
  intl: ^0.20.2
  yaml: ^3.1.3
  mansion: ^0.1.0
  uuid: ^4.5.2
  eterl: ^1.1.0
  env_guard: ^1.3.2
  hmr: ^1.4.1
  glob: ^2.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
